### PR TITLE
Update mobile view layout

### PR DESCRIPTION
**Pull request by or-yam**
# Description

Update mobile-view layout support. 

Fixed follow page

## Type of change

Update bootstrap classes

- [x] Bug fix
- [ ] New feature
- [ ] A documentation update
- [ ] Refactoring

# How Has This Been Tested?

Ran the app in mobile view and went through screens.

image

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I added the relevant people as reviewers to my PR

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
On it! I'll review the changes as soon as possible!

**Comment by vanessa-cooper** [comment]
What's "user-info-xs-none"class name? Looks like it doesn't exists.

**Comment by or-yam** [comment]
@vanessa-cooper I was trying to remove `user-info` class on small devices, but used the wrong syntax.
Thanks for catching that. 
I removed `user-info` class entirely since I didn't see a significant effect on desktop view and couldn't find a way to achieve that with bootstrap classes.

**Review by vanessa-cooper — APPROVED** [review]

**Review by vanessa-cooper — APPROVED** [review]
Excellent job @or-yam! You're now able to merge the PR

**Pull request merged**
